name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn lint
